# Generated by Django 2.2.14 on 2021-06-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('color', models.CharField(max_length=200, verbose_name='color')),
                ('size', models.CharField(max_length=200, verbose_name='size')),
                ('sellPrice', models.FloatField(default=0, verbose_name='sellPrice')),
                ('salePrice', models.FloatField(default=0, verbose_name='salePrice')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
    ]
