# Generated by Django 2.2.14 on 2021-06-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('warranty', models.CharField(max_length=200, verbose_name='warranty')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('productgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductGroup')),
            ],
        ),
    ]
