# Generated by Django 2.2.14 on 2021-06-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usernames', models.CharField(max_length=200, verbose_name='Username')),
                ('passwords', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200, verbose_name='firstName')),
                ('middleName', models.CharField(max_length=200, verbose_name='middleName')),
                ('lastName', models.CharField(max_length=200, verbose_name='lastName')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCard', models.CharField(max_length=50, verbose_name='idCard')),
                ('dob', models.DateTimeField(auto_now_add=True, verbose_name='dob')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('phoneNumber', models.CharField(max_length=200, verbose_name='phoneNumber')),
                ('coin', models.IntegerField(default=0, verbose_name='coin')),
                ('facebookID', models.CharField(max_length=200, verbose_name='facebookID')),
                ('facebookName', models.CharField(max_length=200, verbose_name='facebookName')),
                ('googleEmail', models.CharField(max_length=200, verbose_name='googleEmail')),
                ('googleName', models.CharField(max_length=200, verbose_name='googleName')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.Account')),
                ('fullname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.Fullname')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detailedAddress', models.CharField(max_length=200, verbose_name='detailedAddress')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('country', models.CharField(max_length=200, verbose_name='country')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.User')),
            ],
        ),
    ]
