# Generated by Django 2.2.14 on 2021-06-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isUsing', models.BooleanField(default=False, verbose_name='isUsing')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.User')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(choices=[('VNPost', 'VNPost'), ('GiaoHangTietKiem', 'GiaoHangTietKiem'), ('Now', 'Now'), ('Grab', 'Grab')], default='VNPost', max_length=20)),
                ('type', models.CharField(choices=[('Express', 'Express'), ('Fast', 'Fast'), ('Ordinary', 'Ordinary'), ('Free', 'Free')], default='Express', max_length=20)),
                ('price', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(choices=[('OnDelivery', 'OnDelivery'), ('MOMO', 'MOMO'), ('VNPAY', 'VNPAY'), ('ZaloPay', 'ZaloPay'), ('VisaCard', 'VisaCard'), ('CreditCard', 'CreditCard'), ('BankCard', 'BankCard')], default='OnDelivery', max_length=10)),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('prePayment', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('recipientName', models.CharField(max_length=200, verbose_name='recipientName')),
                ('recipientPhoneNumber', models.CharField(max_length=200, verbose_name='recipientPhoneNumber')),
                ('recipientEmail', models.CharField(max_length=200, verbose_name='recipientEmail')),
                ('detailedAddress', models.CharField(max_length=200, verbose_name='detailedAddress')),
                ('ward', models.CharField(max_length=200, verbose_name='ward')),
                ('district', models.CharField(max_length=200, verbose_name='district')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('country', models.CharField(max_length=200, verbose_name='country')),
                ('note', models.CharField(max_length=200, verbose_name='note')),
                ('status', models.CharField(choices=[('ToPay', 'ToPay'), ('ToShip', 'ToShip'), ('ToReceive', 'ToReceive'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('ReturnRefund', 'ReturnRefund')], default='ToPay', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, verbose_name='dateUpdate')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
            ],
        ),
    ]
